apiVersion: v1
kind: ConfigMap
metadata:
  name: video-processor-config
  namespace: video2frame
data:
  AWS_REGION_NAME: "${AWS_REGION_NAME}"
  S3_INPUT_STORAGE_BUCKET_NAME: "${S3_INPUT_STORAGE_BUCKET_NAME}"
  S3_OUTPUT_STORAGE_BUCKET_NAME: "${S3_OUTPUT_STORAGE_BUCKET_NAME}"
  SNS_EVENT_PUBLISHER_TOPIC_ARN: "${SNS_EVENT_PUBLISHER_TOPIC_ARN}"
  VIDEO_UPLOADED_LISTENER_QUEUE_NAME: "${VIDEO_UPLOADED_LISTENER_QUEUE_NAME}"
