apiVersion: v1
kind: Secret
metadata:
  name: video-processor-secrets
  namespace: video2frame
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_ACCOUNT_ID: "${AWS_ACCOUNT_ID}"
