name: CI / CD Pipeline
on:
  - push
  - workflow_dispatch

env:
  APP_IMAGE: "public.ecr.aws/w8m5i3n3/video2frames-video-processor:latest"

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'Video2Frames/video-processor'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_ACCESS_SECRET }}
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.APP_IMAGE }}
          target: production

  deploy_to_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Apply Namespace
        run: |
          kubectl apply -f k8s/namespace.yml

      - name: Apply ConfigMap
        env:
          AWS_REGION_NAME: ${{ vars.AWS_REGION }}
          S3_INPUT_STORAGE_BUCKET_NAME: ${{ vars.S3_INPUT_STORAGE_BUCKET_NAME }}
          S3_OUTPUT_STORAGE_BUCKET_NAME: ${{ vars.S3_OUTPUT_STORAGE_BUCKET_NAME }}
          SNS_EVENT_PUBLISHER_TOPIC_ARN: ${{ vars.SNS_EVENT_PUBLISHER_TOPIC_ARN }}
          VIDEO_UPLOADED_LISTENER_QUEUE_NAME: ${{ vars.VIDEO_UPLOADED_LISTENER_QUEUE_NAME }}
        run: |
          envsubst < k8s/configmap.yml | kubectl apply -f -

      - name: Apply Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          envsubst < k8s/secrets.yml | kubectl apply -f -

      - name: Apply Deployment
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl rollout restart deployment/video-uploaded-listener -n video2frames

      - name: Apply HPA
        run: |
          kubectl apply -f k8s/hpa.yml
